repos:
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [types-all]

  - repo: local
    hooks:
      - id: cache-integration-tests
        name: Cache Integration Tests
        entry: uv run pytest tests/integration/test_cache_integration.py tests/contract/test_cache_contracts.py -v
        language: system
        pass_filenames: false
        files: ^(src/forkscout/storage/|src/forkscout/display/|src/forkscout/models/).*\.py$

      - id: cache-validation-tests
        name: Cache Validation Tests
        entry: uv run pytest tests/unit/test_cache_validation.py -v
        language: system
        pass_filenames: false
        files: ^src/forkscout/storage/cache_validation\.py$

      - id: model-serialization-check
        name: Model Serialization Check
        entry: python scripts/check_model_serialization.py
        language: system
        pass_filenames: false
        files: ^src/forkscout/models/.*\.py$