ai_summary:
  enabled: true
  model: "gpt-4o-mini"
  max_tokens: 500
  temperature: 0.3
  timeout_seconds: 30
  retry_attempts: 3
  cost_tracking: true
  batch_size: 5
  max_cost_per_session_usd: 5.0
  max_cost_per_request_usd: 0.10
  cost_warning_threshold_usd: 1.0
  usage_logging_enabled: true
  performance_logging_enabled: true

github:
  token: null  # Will be loaded from GITHUB_TOKEN environment variable

logging:
  level: "INFO"
  console_enabled: true
  file_enabled: true